### ISSUE TITLE
[TASK] remove `README.rst`

### ISSUE THREAD

**Issue by LaurenzBeck** [firefly-cpp/NiaAML#95]
## ✅ Task

There are two READMEs in the project. `README.md` seems to be the actively used one.
I did a quick search, and `README.rst` apparently is only mentioned in `tool.poetry.readme` in `pyproject.toml`, which probably is the link to the README, that is used for the [PyPi site](https://pypi.org/project/niaaml/) of NiaAML.
PyPi can handle markdown files, so I would recommend removing `README.rst` to have a single place to maintain.

### 📃 Checklist

- [ ] remove `README.rst`
- [ ] link to `README.md` in `pyproject.toml`
- [ ] check if PyPi renders the README correctly

**Comment by firefly-cpp** [comment]
+1
